# Changes here will be overwritten by Copier
_commit: f812aaa
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: rust
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Time based function caching
project_name: temporal cache
python_version_primary: '3.11'
team: the temporal-cache authors
