dist: xenial
language: node_js
node_js: "10"

cache: 
  - pip

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      language: python
      cache: pip

    - cache: pip
      os: osx
      osx_image: xcode11.2

addons:
  homebrew:
    update: true
    packages:
      - python

install:
    - python3 -m pip install -e .[dev]
    - python3 -m pip install -r requirements.txt

script: make test

after_success:
    - codecov --token 35d2df00-6b24-4d82-8283-52f93865bf55

branches:
  only:
  - master

notifications:
  email: false
